spring.application.name=transaction-ledger
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/transaction-ledger

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/transaction_ledger_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=*
management.health.readiness-state.enabled=true
management.health.liveness-state.enabled=true
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}

app.security.jwt-secret-key=${JWT_SECRET_KEY:}
app.security.jwt-secret-default-value=KWbhrPE3ZPCn76Ng0lOu3dBYDkiQXIKAGXYGmTO5Vw6
app.security.jwt-header=Authorization

logging.level.transaction-ledger.accounts=DEBUG
logging.pattern.level=%5p [${spring.application.name},%X{trace_id},%X{span_id}]

info.app.name=${spring.application.name}
info.app.description=Transaction Ledger Service
info.app.version=1.0.0
